name: WMSK_test_build

on:
  push:
    branches: [ main ]
    tags: [ v**]
  pull_request:
    branches: [ main ]
    tags: [ v**]

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.4'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.16'
    - name: Install apt dependencies
      run: sudo apt-get update && sudo apt-get install libidn11 jq curl wget ninja-build clang pkg-config cmake-data libblkid-dev libgtk-3-dev liblzma-dev flatpak -y
    - name: install appimagekit
      run: wget $(curl -sL https://api.github.com/repos/AppImage/AppImageKit/releases/latest | jq -r '.assets[].browser_download_url' | grep "appimagetool-x86_64.AppImage$") && chmod +x appimagetool-x86_64.AppImage
    - name: flutter get dependencies
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter pub get
    - name: flutter build apk 
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter build apk --release
    - name: flutter build web
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter build web
    - name: flutter config linux
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter config --enable-linux-desktop 
    - name: flutter build linux
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter build linux --release   
    - name: Restore dependencies
      run: dotnet restore
    - name: copy web to dotnet
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/web/* ./WebMacroSoftKeyboard/wwwroot/
    - name: Build linux dotnet
      run: dotnet publish -r linux-x64 -c release

    - name: prepare appimage linxuclient x64 dir
      run: mkdir -p ./appimage/web_macro_soft_keyboard_client_x64.AppDir &&  cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/linux/release/bundle/* ./appimage/web_macro_soft_keyboard_client_x64.AppDir/ && cp ./packaging/AppImage/linuxclient_Apprun ./appimage/web_macro_soft_keyboard_client_x64.AppDir/AppRun && chmod +x ./appimage/web_macro_soft_keyboard_client_x64.AppDir/AppRun && cp ./packaging/logo.png ./appimage/web_macro_soft_keyboard_client_x64.AppDir/WebMarcoSoftKeyboardClient.png && cp ./packaging/AppImage/linux_desktop ./appimage/web_macro_soft_keyboard_client_x64.AppDir/web_macro_soft_keyboard_client_x64.desktop && sed -i "s|%%%VERSION%%%|1.0.0|g" ./appimage/web_macro_soft_keyboard_client_x64.AppDir/web_macro_soft_keyboard_client_x64.desktop
    - name: build appimage linuxclient x64
      run: appimagetool-x86_64.AppImage ./appimage/web_macro_soft_keyboard_client_x64.AppDir/ web_macro_soft_keyboard_client_x64.AppImage

    - name: make upload folders
      run: mkdir upload && mkdir upload/linuxhost_x64 && mkdir upload/linuxclient_x64 && mkdir upload/linuxclient_appimage_x64 && mkdir upload/web && mkdir upload/android 
    - name: copy linux client x64
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/linux/release/bundle/* upload/linuxclient_x64/ 
    - name: copy linux client appimage x64  
      run: cp -rf web_macro_soft_keyboard_client_x64.AppImage upload/linuxclient_appimage_x64/
    - name: copy linux Host x64
      run: cp -rf ./WebMacroSoftKeyboard/bin/Release/net5.0/linux-x64/publish/* upload/linuxhost_x64/
    - name: copy webapp
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/web/* upload/web/
    - name: copy android
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/app/outputs/flutter-apk/* upload/android/
    - name: find uploads
      run: find upload/
    - uses: actions/upload-artifact@v2
      if: ${{ !env.ACT }}
      with:
        name: latest
        path: upload/


  # build_windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       repository: flutter/flutter
  #       ref: master
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: 5.0.x
  #   - name: Add Flutter to path
  #     run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin"
  #   - name: flutter config windows
  #     run: flutter config --enable-windows-desktop
  #   - name: flutter get dependencies
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter pub get
  #   - name: flutter build windows
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter build windows --release
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build Windows dotnet
  #     run: dotnet publish -r win-x64 -c release   


  # build_macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: '12.x'
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '1.22.4'
  #   - name: flutter doctor
  #     run: flutter doctor -v
  #   - name: flutter get dependencies
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter pub get
  #   - name: flutter build ios
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter build ios --release --no-codesign      
  #   - name: flutter config macos
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter config --enable-macos-desktop
  #   - name: flutter build macos
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter build macos --release
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build mac dotnet
  #     run: dotnet publish -r osx-x64 -c release



#  release:
#     name: Release
#     if: startsWith(github.ref, 'refs/tags/v') && ${{ github.event_name == 'push' }}
#     needs:
#     - build_linux  
#     - build_windows
#     - build_macos
#     runs-on: ubuntu-latest
#     steps:
    


# flatpak for future
#

    # - name: prepare flatpak linuxclient
    #   run: mkdir -p ./flatpakbuild/linuxclient && cp  ./packaging/flatpak/org.wmsk.client.yml ./flatpakbuild/linuxclient/ && cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/linux/release/bundle/* ./flatpakbuild/linuxclient/
    # - name: build flatpak linuxclient 
    #   run: cd ./flatpakbuild/linuxclien && flatpak-builder build-dir org.wmsk.client.yml
      # - name: install flatpak SDK
      # run:  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install flathub org.freedesktop.Platform//19.08 org.freedesktop.Sdk//19.08