name: WMSK_test_build

on:
  push:
    branches: [ main ]
    tags: [ v**]
  pull_request:
    branches: [ main ]
    tags: [ v**]

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.4'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.16'
    - name: Install apt dependencies
      run: sudo apt-get update && sudo apt-get install libidn11 ninja-build clang pkg-config cmake-data libblkid-dev libgtk-3-dev liblzma-dev -y
    - name: flutter get dependencies
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter pub get
    - name: flutter build apk
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter build apk
    - name: flutter build web
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter build web
    - name: flutter config linux
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter config --enable-linux-desktop 
    - name: flutter build linux
      working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
      run: flutter build linux    
    - name: Restore dependencies
      run: dotnet restore
    - name: copy web to dotnet
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/web/* ./WebMacroSoftKeyboard/wwwroot/
    - name: Build linux dotnet
      run: dotnet publish -r linux-x64 -c release
    - name: make upload folders
      run: mkdir /upload && mkdir /upload/linuxhost && mkdir /upload/linuxclient && mkdir /upload/web && mkdir /upload/android 
    - name: copy linux client
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/linux/release/bundle/* /upload/linuxclient/
    - name: copy linux Host
      run: cp -rf ./WebMacroSoftKeyboard/bin/Release/net5.0/linux-x64/publish/* /upload/linuxhost/
    - name: copy webapp
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/web/* /upload/web/
    - name: copy android
      run: cp -rf ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client/build/app/outputs/flutter-apk/* /upload/android/
    - name: find uploads
      run: find /upload/
    - uses: actions/upload-artifact@v2
      with:
        name: latest
        path: /upload/


  # build_windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       repository: flutter/flutter
  #       ref: master
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: 5.0.x
  #   - name: Add Flutter to path
  #     run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin"
  #   - name: flutter config windows
  #     run: flutter config --enable-windows-desktop
  #   - name: flutter get dependencies
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter pub get
  #   - name: flutter build windows
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter build windows
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build Windows dotnet
  #     run: dotnet publish -r win-x64 -c release   


  # build_macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: '12.x'
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '1.22.4'
  #   - name: flutter doctor
  #     run: flutter doctor -v
  #   - name: flutter get dependencies
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter pub get
  #   - name: flutter build ios
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter build ios --release --no-codesign      
  #   - name: flutter config macos
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter config --enable-macos-desktop
  #   - name: flutter build macos
  #     working-directory: ./WebMacroSoftKeyboard/ClientAppFlutter/web_macro_soft_keyboard_client    
  #     run: flutter build macos
  #   - name: Restore dependencies
  #     run: dotnet restore
  #   - name: Build mac dotnet
  #     run: dotnet publish -r osx-x64 -c release



#  release:
#     name: Release
#     if: startsWith(github.ref, 'refs/tags/v') && ${{ github.event_name == 'push' }}
#     needs:
#     - build_linux  
#     - build_windows
#     - build_macos
#     runs-on: ubuntu-latest
#     steps:
    
