name: MakroBoard_website_build

on:
  push:
    branches: [ main ]
    tags: [ v**]
    paths:
    - 'Docs/**'
  pull_request:
    branches: [ main ]
    tags: [ v**]
    paths:
    - 'Docs/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: ./Docs/docfx.json
    - name: list build ouput
      run: find ./Docs/_site/


  publish:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, 'forcepublish')
    steps:
    - uses: actions/checkout@v2
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: ./Docs/docfx.json
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        config: ${{ secrets.SSH_CONFIG }} 
        if_key_exists: fail 
    - name: clone pages repo
      run: git clone git@github.com:MakroBoard/makroboard.app.git
    - name: remove old things and add new
      run: rm -rf ./makroboard.app/docs/* && cp -rf ./Docs/_site/* ./makroboard.app/docs/
    - name: push pages repo
      run: git clone git@github.com:MakroBoard/makroboard.app.git
    


